//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int Idcompra { get; set; }
        public Nullable<int> numfactura { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public Nullable<System.DateTime> Feha_compra { get; set; }
        public Nullable<System.DateTime> Fecha_envio { get; set; }
        public Nullable<int> Idproveedor { get; set; }
        public Nullable<decimal> Totalcompra { get; set; }
        public Nullable<System.DateTime> Fecha_pago { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
