//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Idproducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public string Descripcion { get; set; }
        public byte[] Presentacion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Idproveedor { get; set; }
        public Nullable<int> Idcategoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
