//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Idventa { get; set; }
        public Nullable<int> Numfactura { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public Nullable<System.DateTime> Feha_venta { get; set; }
        public Nullable<System.DateTime> Fecha_envio { get; set; }
        public Nullable<int> Idenvio { get; set; }
        public Nullable<int> Idpago { get; set; }
        public Nullable<int> Idproveedor { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Fecha_pago { get; set; }
    
        public virtual Envios Envios { get; set; }
        public virtual Pagos Pagos { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
